### ISSUE TITLE
水印

### ISSUE THREAD

**Issue by J0O0O0O0E** [Dustray/BingWallpaper2#1]
程序很棒谢谢作者,但是同类程序获取的壁纸是没有bing水印的,希望作者也换成没有水印的源.

**Comment by Dustray** [comment]
> 程序很棒谢谢作者,但是同类程序获取的壁纸是没有bing水印的,希望作者也换成没有水印的源.

感谢支持，目前我用的官方源。在官方源下，三个尺寸【1366\*768】【1920\*1080】【1920\*1200】，只有【1920\*1200】是有水印的，其图像质量也更好。
后期我会找一找没有水印的同时图像质量高点的源。

**Comment by J0O0O0O0E** [comment]
> 
> 
> > 程序很棒谢谢作者,但是同类程序获取的壁纸是没有bing水印的,希望作者也换成没有水印的源.
> 
> 感谢支持，目前我用的官方源。在官方源下，三个尺寸【1366*768】【1920*1080】【1920*1200】，只有【1920*1200】是有水印的，其图像质量也更好。
> 后期我会找一找没有水印的同时图像质量高点的源。

原来是这样,感谢神速解答,作者加油!
issue close
